# Generated by Django 4.1.2 on 2022-10-27 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Crossc',
        ),
        migrations.RenameModel(
            old_name='Sneakercard',
            new_name='Crosscard',
        ),
    ]
