# Generated by Django 4.2.4 on 2023-09-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('room', 'Комната'), ('tenant', 'Квартирант'), ('hotel', 'Гостиница'), ('commercial', 'Коммерческая недвижимость')], max_length=20)),
                ('ad_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], max_length=10)),
                ('photo', models.ImageField(upload_to='property_photos/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_city', models.CharField(max_length=100)),
                ('location_district', models.CharField(max_length=100)),
                ('location_street', models.CharField(max_length=100)),
                ('views', models.PositiveIntegerField(default=0)),
                ('num_rooms', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('floor', models.PositiveIntegerField()),
                ('total_floors', models.PositiveIntegerField()),
                ('additional_conditions', models.TextField()),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('likes', models.ManyToManyField(related_name='liked_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_properties', models.ManyToManyField(related_name='liked_by_users', to='main.property')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
