# Generated by Django 4.2.4 on 2023-09-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Apartment', 'Квартира'), ('Room', 'Комната'), ('Dormitory', 'Квартирант'), ('Hotel', 'Гостиница'), ('Commercial', 'Коммерческая недвижимость')], max_length=20)),
                ('publication_type', models.CharField(choices=[('Sale', 'Продажа'), ('Rent', 'Аренда')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_city', models.CharField(max_length=255)),
                ('location_district', models.CharField(max_length=255)),
                ('location_street', models.CharField(max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('num_rooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('floor', models.IntegerField()),
                ('total_floors', models.IntegerField()),
                ('extras', models.TextField(blank=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_properties',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_listings', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='main.listing'),
        ),
    ]
