# Generated by Django 4.1.2 on 2022-10-06 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Brand Name')),
            ],
        ),
        migrations.CreateModel(
            name='Sneakercard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Name')),
                ('desc', models.CharField(max_length=100, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('snimage', models.ImageField(upload_to='main', verbose_name='Photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brand', verbose_name='Brand')),
            ],
        ),
    ]
