# Generated by Django 4.1.2 on 2022-10-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakercard',
            old_name='snimage',
            new_name='image',
        ),
    ]
